#!/usr/bin/env python3
"""FireSplitHamiltonian: write the two ignition lines, line_0.csv and line_34.csv.

    python3 make_ignition_lines.py

Both are the same 1 km line, perpendicular to the wind and centred STANDOFF
upwind of the domain centre; the 34 deg line is the 0 deg one (and its wind)
rigidly rotated by 34 deg about the domain centre. The constants below must
match CENTRE and STANDOFF in check_firesplithamiltonian.py and the wind in
inputs_baseline_* / inputs_split_*: the 34 deg wind is 4.005 m/s at 34 deg,
(3.3203, 2.2396) m/s.
"""

import math

CENTRE = 2400.0    # domain centre, x and y [m]
STANDOFF = 1200.0  # line midpoint, upwind of the centre [m]
HALF = 500.0       # half the line length [m]
ANGLES = (0, 34)   # wind headings [deg], math convention, 0 = +x


for ang in ANGLES:
    th = math.radians(ang)
    c, s = math.cos(th), math.sin(th)
    cx, cy = CENTRE - STANDOFF * c, CENTRE - STANDOFF * s   # midpoint, upwind of the centre
    px, py = -s, c                                          # line direction, perpendicular to the wind
    p1 = (cx - HALF * px, cy - HALF * py)
    p2 = (cx + HALF * px, cy + HALF * py)
    with open(f"line_{ang}.csv", "w") as f:
        f.write(f"# Finite ignition line, {2 * HALF:.0f} m long, perpendicular to a {ang} deg wind (math convention,\n")
        f.write(f"# 0 = +x), centred {STANDOFF:.0f} m upwind of the domain centre ({CENTRE:.0f}, {CENTRE:.0f}). "
                f"The {ang} deg case is\n")
        f.write(f"# the 0 deg case rigidly rotated by {ang} deg about the domain centre.\n")
        f.write(f"# Generated by make_ignition_lines.py.\n")
        f.write(f"{p1[0]:.3f} {p1[1]:.3f}\n{p2[0]:.3f} {p2[1]:.3f}\n")
    print(f"line_{ang}.csv: ({p1[0]:.3f}, {p1[1]:.3f}) -> ({p2[0]:.3f}, {p2[1]:.3f})")
