if (ERF_ENABLE_LNG)
  add_subdirectory(LNG_BuildOnly)
  add_subdirectory(PoolEvap)
  add_subdirectory(LNG_ScalarInjection)
  add_subdirectory(LNG_WindExtraction)
  add_subdirectory(LNG_GravityCurrent)
  add_subdirectory(LNG_Output)
  add_subdirectory(LNG_Regulatory)
  add_subdirectory(LNG_SpillSchedule)
endif()
